FROM busybox:1.36.0

WORKDIR /code
# https://opentelemetry.io/docs/instrumentation/java/automatic/
RUN ["wget", "https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar"]