receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  logging:
    loglevel: debug
  otlp/elastic: 
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "nbs-horizon-dev-cluster.apm.eu-west-2.aws.cloud.es.io:443"  
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer <bearer token>" 

processors:
  batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/elastic]
      processors: [batch]
